"use client";

import { AppConfig } from "@/lib/config";
import { Text, View, StyleSheet, Font } from "@react-pdf/renderer";
import { formatDate } from "date-fns";

// ─── Types ──────────────────────────────────────────────────────────────────────
interface PDFHeaderProps {
  headerColor?: string;
  reportDate?: string;
}

interface PDFFooterProps {
  pageNumber?: string;
  totalPages?: string;
}

// ─── Shared Styles ─────────────────────────────────────────────────────────────
export const pdfLayoutStyles = StyleSheet.create({
  // ── Header ──────────────────────────────────────────────────────────────────
  header: {
    marginBottom: 8,
    padding: 6,
  },
  headerCompanyName: {
    fontSize: 36,
    fontFamily: "Revue",
    textAlign: "center",
    marginBottom: 2,
  },
  headerTagline: {
    fontSize: 16,
    textAlign: "center",
    fontFamily: "Roboto",
    fontWeight: "bold",
    marginBottom: 1,
  },
  headerSubTagline: {
    fontSize: 15,
    textAlign: "center",
    fontFamily: "Roboto",
    fontWeight: "semibold",
    marginBottom: 3,
  },
  headerDivider: {
    borderBottomWidth: 2,
    borderBottomColor: "#000000",
    marginVertical: 3,
  },
  headerAddress: {
    fontSize: 12,
    marginVertical: 4,
    textAlign: "center",
    color: "#333333",
  },
  headerDateRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  headerDate: {
    fontSize: 10,
    fontFamily: "Roboto",
    fontWeight: "semibold",
  },

  // ── Footer ─────────────────────────────────────────────────────────────────
  footer: {
    position: "absolute",
    bottom: 12,
    left: 20,
    right: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 0.5,
    borderTopColor: "#999999",
    paddingTop: 3,
  },
  footerText: {
    fontSize: 8,
    color: "#666666",
  },
});

// ─── Reusable Header Component ──────────────────────────────────────────────────
export const PDFHeader = ({
  reportDate,
  headerColor = "black",
}: PDFHeaderProps) => (
  <View style={pdfLayoutStyles.header}>
    <Text style={[pdfLayoutStyles.headerCompanyName, { color: headerColor }]}>
      {AppConfig.company.name}
    </Text>
    <Text style={pdfLayoutStyles.headerTagline}>
      {AppConfig.company.tagLine}
    </Text>
    <Text style={pdfLayoutStyles.headerSubTagline}>
      {AppConfig.company.subTagLine}
    </Text>
    <View style={pdfLayoutStyles.headerDivider} />
    <Text style={pdfLayoutStyles.headerAddress}>
      {AppConfig.company.address}
    </Text>
    <View style={pdfLayoutStyles.headerDateRow}>
      <Text style={pdfLayoutStyles.headerDate}>Date: {reportDate}</Text>
    </View>
  </View>
);

// ─── Reusable Footer Component ──────────────────────────────────────────────────
export const PDFFooter = () => (
  <View style={pdfLayoutStyles.footer} fixed>
    <Text
      style={pdfLayoutStyles.footerText}
      render={({ pageNumber, totalPages }) =>
        `Page ${pageNumber} of ${totalPages}`
      }
    />
    <Text style={pdfLayoutStyles.footerText}>
      {`Generated by ${AppConfig.company.name} on ${formatDate(new Date(), "dd MMM yyyy, hh:mm a")}`}
    </Text>
  </View>
);
